### PR TITLE
fix: add a divider line between Surahs in insert page cmd in callout format

### LINKED ISSUE #45: UI: insert page command don't enter a new line if there are multiple Surahs on the same page
# Insert page command don't enter a new line if there are multiple Surahs on the same page

Scenario in Obsidian,
1. Open the command palette
2. Write "Quran: insert Page"
3. Write "604"

**Current:**
no separation between Surahs **(check screenshot)**

Image

**Expected:**
each Surah's beginning to be in a new line **(check screenshot)**

Image

Obsidian version: 1.12.7 (Windows)
plugin version: 1.13.0

### PR DESCRIPTION
**Pull request by MohamedMedhat21**
### What changes were made
Add a divider line between Surahs in the insert page command in callout format
resolve #45 
### Why were the changes made
to make good visibility and separation between Surahs on the same page
### How to test the changes
manually by inserting a page specially that contains more than one Surah (ex. page No. 604)
### Any breaking changes
No
---
### Demo

output

image

### CODE REVIEW

File: src/FzfPageAyahModal.ts [hunk 1]
```diff
@@ -112,7 +112,10 @@ export class FzfPageAyahModal extends SuggestModal<PageAyahItem> {
     } else {
       const type = calloutType || "quran";
       content = `> [!${type}] ${header}\n> `;
-      ayahs.forEach((ayah) => {
+      ayahs.forEach((ayah, index) => {
+        if (index > 0 && ayah.surah_id !== ayahs[index - 1]?.surah_id) {
+          content += `\n>  ---\n> `;
```
Comment (AmmarCodes) [inline src/FzfPageAyahModal.ts]:
```suggestion
          content += `\n> \n> `;
```

can we make it just an empty line?

Comment (MohamedMedhat21) [reply src/FzfPageAyahModal.ts]: done
@AmmarCodes 
edit:
image
